sudo: required

language: go

services:
  - docker

go:
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/pierrre/gotestcover github.com/go-sql-driver/mysql github.com/lib/pq github.com/stretchr/testify/require github.com/stretchr/testify/assert
  - go get ./...

script:
  - go vet -x .
  - gotestcover -coverprofile="cover.out" -race -covermode="count" .
  - goveralls -coverprofile="cover.out"
